version: "3.9"
services:
  web:
    image: nginx:latest
    environment: 
      - DOCKER_ENV=true
      - FLASK_SERVER_ADDR=backend:9090  
    volumes:
      -  ./nginx/nginx.conf:/tmp/nginx.conf
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGTERM
    environment:
      - DOCKER_ENV=true
      - FLASK_SERVER_PORT=9090
      - CONNECTION_STRING=${CONNECTION_STRING}
    volumes:
      - ./flask:/src
